#pragma once

#define LLAMA_MAX_DATA_DOMAIN_DEPTH 3

// LLAMA_INTERNAL_PARSE_DS_CONTENT_3

#define LLAMA_INTERNAL_PARSE_TUPLE_3( Tuple ) \
	BOOST_PP_IIF( BOOST_PP_EQUAL( BOOST_PP_TUPLE_ELEM(1, Tuple), LLAMA_DATESTRUCT), \
		llama::DateStruct< \
			LLAMA_INTERNAL_PARSE_DS_CONTENT_4( BOOST_PP_TUPLE_ELEM(2, Tuple) ) \
		> \
	, \
		BOOST_PP_TUPLE_ELEM(2, Tuple) )

#define LLAMA_INTERNAL_PARSE_DS_CONTENT_LOOP_3( Z, N, Content ) \
	LLAMA_INTERNAL_PARSE_TUPLE_3( BOOST_PP_TUPLE_ELEM(N, Content) )

#define LLAMA_INTERNAL_PARSE_DS_CONTENT_3( Content ) \
	BOOST_PP_REPEAT_3( BOOST_PP_TUPLE_SIZE( Content ), LLAMA_INTERNAL_PARSE_DS_CONTENT_LOOP_3, Content )

// LLAMA_INTERNAL_PARSE_DS_CONTENT_2

#define LLAMA_INTERNAL_PARSE_TUPLE_2( Tuple ) \
	BOOST_PP_IIF( BOOST_PP_EQUAL( BOOST_PP_TUPLE_ELEM(1, Tuple), LLAMA_DATESTRUCT), \
		llama::DateStruct< \
			LLAMA_INTERNAL_PARSE_DS_CONTENT_3( BOOST_PP_TUPLE_ELEM(2, Tuple) ) \
		> \
	, \
		BOOST_PP_TUPLE_ELEM(2, Tuple))

#define LLAMA_INTERNAL_PARSE_DS_CONTENT_LOOP_2( Z, N, Content ) \
	(BOOST_PP_COMMA_IF(N)) \
	LLAMA_INTERNAL_PARSE_TUPLE_2( BOOST_PP_TUPLE_ELEM(N, Content))

#define LLAMA_INTERNAL_PARSE_DS_CONTENT_2( Content ) \
	BOOST_PP_REPEAT_2( BOOST_PP_TUPLE_SIZE( Content ), LLAMA_INTERNAL_PARSE_DS_CONTENT_LOOP_2, Content )

// LLAMA_INTERNAL_PARSE_DS_CONTENT_1

#define LLAMA_INTERNAL_PARSE_TUPLE_1( Tuple ) \
	BOOST_PP_IIF( BOOST_PP_EQUAL( BOOST_PP_TUPLE_ELEM(1, Tuple), LLAMA_DATESTRUCT), \
		llama::DateStruct< \
			LLAMA_INTERNAL_PARSE_DS_CONTENT_2( BOOST_PP_TUPLE_ELEM(2, Tuple) ) \
		> \
	, \
		BOOST_PP_TUPLE_ELEM(2, Tuple))

#define LLAMA_INTERNAL_PARSE_DS_CONTENT_LOOP_1( Z, N, Content ) \
	BOOST_PP_COMMA_IF( N ) \
	LLAMA_INTERNAL_PARSE_TUPLE_1( BOOST_PP_TUPLE_ELEM(N, Content) )

#define LLAMA_INTERNAL_PARSE_DS_CONTENT_1( Content ) \
	BOOST_PP_REPEAT_1( BOOST_PP_TUPLE_SIZE( Content ), LLAMA_INTERNAL_PARSE_DS_CONTENT_LOOP_1, Content )

#define LLAMA_INTERNAL_COMMA() ,
