# see also: https://docs.readthedocs.io/en/stable/config-file/v2.html#supported-settings
version: 2
formats:
    - htmlzip
    - pdf
    - epub
build:
    os: ubuntu-22.04
    tools:
        python: "3.11"
sphinx:
    builder: html
    configuration: docs/source/conf.py
    fail_on_warning: false
python:
    install:
        - requirements: docs/requirements.txt
