var hierarchy =
[
    [ "AddKernel< ProblemSize, Elems >", "structAddKernel.html", null ],
    [ "llama::allocator::internal::AlignmentAllocator< T, Alignment >", "structllama_1_1allocator_1_1internal_1_1AlignmentAllocator.html", null ],
    [ "llama::mapping::AoS< T_UserDomain, T_DatumDomain, LinearizeUserDomainFunctor >", "structllama_1_1mapping_1_1AoS.html", null ],
    [ "llama::mapping::AoSoA< T_UserDomain, T_DatumDomain, Lanes, LinearizeUserDomainFunctor >", "structllama_1_1mapping_1_1AoSoA.html", null ],
    [ "llama::Array< T, N >", "structllama_1_1Array.html", null ],
    [ "llama::Array< BlobType, Mapping::blobCount >", "structllama_1_1Array.html", null ],
    [ "llama::Array< std::size_t, Dim >", "structllama_1_1Array.html", [
      [ "llama::ArrayDomain< Dim >", "structllama_1_1ArrayDomain.html", null ]
    ] ],
    [ "llama::ArrayDomainIndexRange< Dim >", "structllama_1_1ArrayDomainIndexRange.html", null ],
    [ "llama::internal::Assign", "structllama_1_1internal_1_1Assign.html", null ],
    [ "tag::B", "structtag_1_1B.html", null ],
    [ "BlurKernel< Elems, KernelSize, ElemsPerBlock >", "structBlurKernel.html", null ],
    [ "llama::mapping::tree::functor::internal::ChangeNodeChildsRuntimeFunctor", "structllama_1_1mapping_1_1tree_1_1functor_1_1internal_1_1ChangeNodeChildsRuntimeFunctor.html", null ],
    [ "Chrono", "structChrono.html", null ],
    [ "llama::mapping::tree::internal::CreateTreeElement< Tag, DatumDomain, CountType >", "structllama_1_1mapping_1_1tree_1_1internal_1_1CreateTreeElement.html", null ],
    [ "llama::mapping::tree::internal::CreateTreeElement< Tag, DatumStruct< DatumElements... >, CountType >", "structllama_1_1mapping_1_1tree_1_1internal_1_1CreateTreeElement_3_01Tag_00_01DatumStruct_3_01Datc3ccbed44d6a97714ab93e0f6f41fa37.html", null ],
    [ "llama::DatumCoord< Coords >", "structllama_1_1DatumCoord.html", null ],
    [ "llama::DatumCoord<>", "structllama_1_1DatumCoord_3_4.html", null ],
    [ "llama::internal::DatumCoordCommonPrefixIsBiggerImpl< First, Second >", "structllama_1_1internal_1_1DatumCoordCommonPrefixIsBiggerImpl.html", null ],
    [ "llama::internal::DatumCoordCommonPrefixIsBiggerImpl< DatumCoord< Coords1... >, DatumCoord< Coords2... > >", "structllama_1_1internal_1_1DatumCoordCommonPrefixIsBiggerImpl_3_01DatumCoord_3_01Coords1_8_8_8_0a9ff93cdac6b21bec7503cb13b2b2baf.html", null ],
    [ "llama::internal::DatumCoordCommonPrefixIsSameImpl< First, Second >", "structllama_1_1internal_1_1DatumCoordCommonPrefixIsSameImpl.html", null ],
    [ "llama::internal::DatumCoordCommonPrefixIsSameImpl< DatumCoord< Coords1... >, DatumCoord< Coords2... > >", "structllama_1_1internal_1_1DatumCoordCommonPrefixIsSameImpl_3_01DatumCoord_3_01Coords1_8_8_8_01_6cecc45c39dad0f9ee30012d1ddccac5.html", null ],
    [ "llama::internal::DivideAssign", "structllama_1_1internal_1_1DivideAssign.html", null ],
    [ "tag::G", "structtag_1_1G.html", null ],
    [ "llama::internal::GetCoordFromTagsImpl< DatumDomain, DatumCoord, Tags >", "structllama_1_1internal_1_1GetCoordFromTagsImpl.html", null ],
    [ "llama::internal::GetCoordFromTagsImpl< DatumDomain, DatumCoord >", "structllama_1_1internal_1_1GetCoordFromTagsImpl_3_01DatumDomain_00_01DatumCoord_01_4.html", null ],
    [ "llama::internal::GetCoordFromTagsImpl< DatumStruct< DatumElements... >, DatumCoord< ResultCoords... >, FirstTag, Tags... >", "structllama_1_1internal_1_1GetCoordFromTagsImpl_3_01DatumStruct_3_01DatumElements_8_8_8_01_4_00_d11d95071a2bfb84786da221f3c394b2.html", null ],
    [ "llama::internal::GetCoordFromTagsRelativeImpl< DatumDomain, BaseDatumCoord, Tags >", "structllama_1_1internal_1_1GetCoordFromTagsRelativeImpl.html", null ],
    [ "llama::internal::GetTagsImpl< CurrTag, DatumDomain, DatumCoord >", "structllama_1_1internal_1_1GetTagsImpl.html", null ],
    [ "llama::internal::GetTagsImpl< CurrTag, DatumStruct< DatumElements... >, DatumCoord< FirstCoord, Coords... > >", "structllama_1_1internal_1_1GetTagsImpl_3_01CurrTag_00_01DatumStruct_3_01DatumElements_8_8_8_01_4c046d237a9f593ba15b9256149e86d7e.html", null ],
    [ "llama::internal::GetTagsImpl< CurrTag, T, DatumCoord<> >", "structllama_1_1internal_1_1GetTagsImpl_3_01CurrTag_00_01T_00_01DatumCoord_3_4_01_4.html", null ],
    [ "llama::internal::GetTypeImpl< DatumDomain, DatumCoordOrTags >", "structllama_1_1internal_1_1GetTypeImpl.html", null ],
    [ "llama::internal::GetTypeImpl< DatumStruct< Children... >, DatumCoord< HeadCoord, TailCoords... > >", "structllama_1_1internal_1_1GetTypeImpl_3_01DatumStruct_3_01Children_8_8_8_01_4_00_01DatumCoord_38455032b17ec18cace1abc9c6eb3a82e.html", null ],
    [ "llama::internal::GetTypeImpl< T, DatumCoord<> >", "structllama_1_1internal_1_1GetTypeImpl_3_01T_00_01DatumCoord_3_4_01_4.html", null ],
    [ "HeatEquationKernel", "structHeatEquationKernel.html", null ],
    [ "llama::mapping::tree::functor::Idem", "structllama_1_1mapping_1_1tree_1_1functor_1_1Idem.html", null ],
    [ "integral_constant", null, [
      [ "std::tuple_size< llama::Array< T, N > >", "structstd_1_1tuple__size_3_01llama_1_1Array_3_01T_00_01N_01_4_01_4.html", null ],
      [ "std::tuple_size< llama::ArrayDomain< N > >", "structstd_1_1tuple__size_3_01llama_1_1ArrayDomain_3_01N_01_4_01_4.html", null ]
    ] ],
    [ "is_same", null, [
      [ "llama::internal::GetCoordFromTagsImpl< DatumStruct< DatumElements... >, DatumCoord< ResultCoords... >, FirstTag, Tags... >::HasTag< DatumElement >", "structllama_1_1internal_1_1GetCoordFromTagsImpl_3_01DatumStruct_3_01DatumElements_8_8_8_01_4_00_00cf5963767cde61bf576c0eaa4b5770.html", null ]
    ] ],
    [ "iterator_facade", null, [
      [ "llama::ArrayDomainIndexIterator< Dim >", "structllama_1_1ArrayDomainIndexIterator.html", null ]
    ] ],
    [ "llama::mapping::tree::Leaf< T_Identifier, T_Type, CountType >", "structllama_1_1mapping_1_1tree_1_1Leaf.html", null ],
    [ "llama::mapping::tree::functor::LeafOnlyRT", "structllama_1_1mapping_1_1tree_1_1functor_1_1LeafOnlyRT.html", null ],
    [ "llama::mapping::LinearizeUserDomainCpp", "structllama_1_1mapping_1_1LinearizeUserDomainCpp.html", null ],
    [ "llama::mapping::LinearizeUserDomainFortran", "structllama_1_1mapping_1_1LinearizeUserDomainFortran.html", null ],
    [ "llama::mapping::LinearizeUserDomainMorton", "structllama_1_1mapping_1_1LinearizeUserDomainMorton.html", null ],
    [ "llama::mapping::tree::Mapping< T_UserDomain, T_DatumDomain, TreeOperationList >", "structllama_1_1mapping_1_1tree_1_1Mapping.html", null ],
    [ "tag::Mass", "structtag_1_1Mass.html", null ],
    [ "usellama::tag::Mass", "structusellama_1_1tag_1_1Mass.html", null ],
    [ "llama::mapping::tree::internal::MergeFunctors< Tree, TreeOperationList >", "structllama_1_1mapping_1_1tree_1_1internal_1_1MergeFunctors.html", null ],
    [ "llama::mapping::tree::internal::MergeFunctors< BasicTree, TreeOperationList >", "structllama_1_1mapping_1_1tree_1_1internal_1_1MergeFunctors.html", null ],
    [ "llama::mapping::tree::internal::MergeFunctors< ResultTree, boost::mp11::mp_drop_c< llama::Tuple< Operations... >, 1 > >", "structllama_1_1mapping_1_1tree_1_1internal_1_1MergeFunctors.html", null ],
    [ "llama::mapping::tree::internal::MergeFunctors< Tree, Tuple< Operations... > >", "structllama_1_1mapping_1_1tree_1_1internal_1_1MergeFunctors_3_01Tree_00_01Tuple_3_01Operations_8_8_8_01_4_01_4.html", null ],
    [ "llama::mapping::tree::internal::MergeFunctors< Tree, Tuple<> >", "structllama_1_1mapping_1_1tree_1_1internal_1_1MergeFunctors_3_01Tree_00_01Tuple_3_4_01_4.html", null ],
    [ "llama::internal::MinusAssign", "structllama_1_1internal_1_1MinusAssign.html", null ],
    [ "llama::internal::ModuloAssign", "structllama_1_1internal_1_1ModuloAssign.html", null ],
    [ "st::Momentum", "structst_1_1Momentum.html", null ],
    [ "MoveKernel< ProblemSize, Elems >", "structMoveKernel.html", null ],
    [ "llama::mapping::tree::functor::MoveRTDown< TreeCoord, Amount >", "structllama_1_1mapping_1_1tree_1_1functor_1_1MoveRTDown.html", null ],
    [ "llama::internal::mp_unwrap_sizes_impl< L >", "structllama_1_1internal_1_1mp__unwrap__sizes__impl.html", null ],
    [ "llama::internal::mp_unwrap_sizes_impl< L< T... > >", "structllama_1_1internal_1_1mp__unwrap__sizes__impl_3_01L_3_01T_8_8_8_01_4_01_4.html", null ],
    [ "llama::internal::MultiplyAssign", "structllama_1_1internal_1_1MultiplyAssign.html", null ],
    [ "llama::mapping::tree::Node< T_Identifier, T_ChildrenTuple, CountType >", "structllama_1_1mapping_1_1tree_1_1Node.html", null ],
    [ "llama::NoName", "structllama_1_1NoName.html", null ],
    [ "llama::NrAndOffset", "structllama_1_1NrAndOffset.html", null ],
    [ "llama::mapping::One< T_UserDomain, T_DatumDomain >", "structllama_1_1mapping_1_1One.html", null ],
    [ "st::Options", "structst_1_1Options.html", null ],
    [ "manualAoS::Particle", "structmanualAoS_1_1Particle.html", null ],
    [ "llama::internal::PlusAssign", "structllama_1_1internal_1_1PlusAssign.html", null ],
    [ "tag::Pos", "structtag_1_1Pos.html", null ],
    [ "usellama::tag::Pos", "structusellama_1_1tag_1_1Pos.html", null ],
    [ "st::Pos", "structst_1_1Pos.html", null ],
    [ "tag::R", "structtag_1_1R.html", null ],
    [ "llama::allocator::internal::AlignmentAllocator< T, Alignment >::rebind< T2 >", "structllama_1_1allocator_1_1internal_1_1AlignmentAllocator_1_1rebind.html", null ],
    [ "SetZeroFunctor< VirtualDatum >", "structSetZeroFunctor.html", null ],
    [ "llama::allocator::SharedPtr< Alignment >", "structllama_1_1allocator_1_1SharedPtr.html", null ],
    [ "llama::mapping::SoA< T_UserDomain, T_DatumDomain, LinearizeUserDomainFunctor >", "structllama_1_1mapping_1_1SoA.html", null ],
    [ "llama::allocator::Stack< BytesToReserve >", "structllama_1_1allocator_1_1Stack.html", null ],
    [ "stbi_io_callbacks", "structstbi__io__callbacks.html", null ],
    [ "common::ThreadsElemsDistribution< T_Acc, blockSize, hardwareThreads >", "structcommon_1_1ThreadsElemsDistribution.html", null ],
    [ "llama::mapping::Trace< Mapping >", "structllama_1_1mapping_1_1Trace.html", null ],
    [ "llama::mapping::tree::TreeCoordElement< ChildIndex, ArrayIndexType >", "structllama_1_1mapping_1_1tree_1_1TreeCoordElement.html", null ],
    [ "llama::Tuple< Elements >", "structllama_1_1Tuple.html", null ],
    [ "llama::Tuple< Elements... >", "structllama_1_1Tuple.html", null ],
    [ "llama::Tuple< T_FirstElement >", "structllama_1_1Tuple_3_01T__FirstElement_01_4.html", null ],
    [ "llama::Tuple< T_FirstElement, Elements... >", "structllama_1_1Tuple_3_01T__FirstElement_00_01Elements_8_8_8_01_4.html", null ],
    [ "llama::Tuple<>", "structllama_1_1Tuple_3_4.html", null ],
    [ "std::tuple_element< I, llama::Array< T, N > >", "structstd_1_1tuple__element_3_01I_00_01llama_1_1Array_3_01T_00_01N_01_4_01_4.html", null ],
    [ "std::tuple_element< I, llama::ArrayDomain< N > >", "structstd_1_1tuple__element_3_01I_00_01llama_1_1ArrayDomain_3_01N_01_4_01_4.html", null ],
    [ "llama::internal::TupleReplaceImpl< Pos, Tuple, Replacement >", "structllama_1_1internal_1_1TupleReplaceImpl.html", null ],
    [ "llama::internal::TupleReplaceImpl< 0, Tuple< Elements... >, Replacement >", "structllama_1_1internal_1_1TupleReplaceImpl_3_010_00_01Tuple_3_01Elements_8_8_8_01_4_00_01Replacement_01_4.html", null ],
    [ "llama::internal::TupleReplaceImpl< 0, Tuple< OneElement >, Replacement >", "structllama_1_1internal_1_1TupleReplaceImpl_3_010_00_01Tuple_3_01OneElement_01_4_00_01Replacement_01_4.html", null ],
    [ "llama::internal::TupleTransformHelper< Seq >", "structllama_1_1internal_1_1TupleTransformHelper.html", null ],
    [ "llama::internal::TupleTransformHelper< std::index_sequence< Is... > >", "structllama_1_1internal_1_1TupleTransformHelper_3_01std_1_1index__sequence_3_01Is_8_8_8_01_4_01_4.html", null ],
    [ "UpdateKernel< ProblemSize, Elems, BlockSize >", "structUpdateKernel.html", null ],
    [ "manualAoS::Vec", "structmanualAoS_1_1Vec.html", null ],
    [ "llama::allocator::Vector< Alignment >", "structllama_1_1allocator_1_1Vector.html", null ],
    [ "manualAoS::Vector", "structmanualAoS_1_1Vector.html", null ],
    [ "usellama::tag::Vel", "structusellama_1_1tag_1_1Vel.html", null ],
    [ "tag::Vel", "structtag_1_1Vel.html", null ],
    [ "llama::View< T_Mapping, BlobType >", "structllama_1_1View.html", null ],
    [ "llama::VirtualDatum< T_View, BoundDatumDomain, OwnView >", "structllama_1_1VirtualDatum.html", null ],
    [ "llama::VirtualView< T_ParentViewType >", "structllama_1_1VirtualView.html", null ],
    [ "st::Weight", "structst_1_1Weight.html", null ],
    [ "llama::mapping::tree::internal::WrapInNNodes< Leaf, Count >", "structllama_1_1mapping_1_1tree_1_1internal_1_1WrapInNNodes.html", null ],
    [ "llama::mapping::tree::internal::WrapInNNodes< Leaf, 0 >", "structllama_1_1mapping_1_1tree_1_1internal_1_1WrapInNNodes_3_01Leaf_00_010_01_4.html", null ],
    [ "usellama::tag::X", "structusellama_1_1tag_1_1X.html", null ],
    [ "tag::X", "structtag_1_1X.html", null ],
    [ "st::X", "structst_1_1X.html", null ],
    [ "tag::Y", "structtag_1_1Y.html", null ],
    [ "st::Y", "structst_1_1Y.html", null ],
    [ "usellama::tag::Y", "structusellama_1_1tag_1_1Y.html", null ],
    [ "usellama::tag::Z", "structusellama_1_1tag_1_1Z.html", null ],
    [ "st::Z", "structst_1_1Z.html", null ],
    [ "tag::Z", "structtag_1_1Z.html", null ]
];